### ISSUE TITLE
Provide example of how to use

### ISSUE THREAD

**Issue by skimonkey** [znetstar/tor-router#9]
Please provide a samplke of how I could use this lib.
Eg sample request from postman via tor proxy to http://google.com

**Comment by znetstar** [comment]
You can interact with Tor Router 3 ways.

1. You can start up Tor Router on the command line, [example here](https://github.com/znetstar/tor-router#usage).
2. You can interact with Tor Router via the JSON RPC Interface, [example here](https://github.com/znetstar/tor-router/wiki/Control-Server).
3. You can include Tor Router in your application as a node module the [api documentation](https://tor-router.docs.zacharyboyd.nyc/) would help with that.

I don't use Postman, but if it can use a HTTP proxy that it should work with Tor Router. Run Tor Router with `npx tor-router -h -j X` where X is the number of instances you want. Then tell Postman to connect to http://localhost:9080.

**Comment by skimonkey** [comment]
Thanks,  Im running the tor-router in a docker container and attempting to route requests via it from a node app in another docker container. I am using https-proxy-agent and and node https but always get 
```
Error: connect EADDRNOTAVAIL 0.0.0.0:9053
```
I have my proxy set as 
```
http://0.0.0.0:9053/
```
Is this correct???

I can now route requests via postman using the following url but not from within my node app
```
http://0.0.0.0:9053@whatsmyip.org/
```

**Comment by znetstar** [comment]
"0.0.0.0" means all network interfaces in your container. It is not an actual IP Address, which is why it is telling you "0.0.0.0" ADDRNOTAVAIL (Address not available). 

First, you need to make sure that the container exposes the port to the host: `docker run -p 9053:9053 znetstar/tor-router -j 1 -h 9053`

Then you need to connect to localhost on the loopback network interface (in other words tell the proxy to connect to the computer you're using). The address for localhost is "127.0.0.1" so your proxy address is "http://127.0.0.1:9053".

**Comment by skimonkey** [comment]
I had previously tried a proxy setting of 127.0.0.1:9053 and localhost:9053 but neither worked for me. I also tried setting a different ip address and port but still did not work.
I havent tried from code yet but I will do so in the morning. I feel I must be mis-understanding something..!

Here are a few images of my settings/attempts from postman 
![docker-tor-router](https://user-images.githubusercontent.com/1823176/46982792-af274d00-d0d5-11e8-9d4e-69cdb5bea6cb.PNG)
![postman-proxy](https://user-images.githubusercontent.com/1823176/46982797-b51d2e00-d0d5-11e8-8835-60864d7a7148.PNG)
![postman-test](https://user-images.githubusercontent.com/1823176/46982800-b6e6f180-d0d5-11e8-895c-2f96c694eb3a.PNG)

**Comment by skimonkey** [comment]
Eventually got this to work from code. I never got it work from postman so maybe its just not possible.

From code I used the following lib to make the request via the tor-router proxy container.
https://www.npmjs.com/package/tor-request
